const http=require('http');
http.createServer((req,res)=>{
    res.writeHead(200,{'Content-Type':'application/json'});
    res.write(JSON.stringify(
        [{
            "name":"shivani",
            "address":"shimla"
        },
    {
        "name":"abhay",
        "address":"bilaspur"
    },
{
    "name":"sushmita",
    "address":"panol"
},
]
    ));
    res.end();
}).listen(9500);
